model_path: "/media/scratch1/jonfrey/models/runs/pixelwise_refinement/learn_segmentation/_" #debug
estimator_restore: true
estimator_load: "/media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_model_26_0.012863246640872631.pth"
refiner_restore: false
refiner_load: "/media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_refine_model_69_0.009449292959118935.pth"
restore_deepim_refiner: "/media/scratch1/jonfrey/models/pretrained_flownet/FlowNetModels/pytorch/flownets_from_caffe.pth.tar"

checkpoint_restore: False
checkpoint_load: "/media/scratch1/jonfrey/models/runs/pixelwise_refinement/learn_segmentation/2020-09-09T06:30:19__/epoch=21-avg_val_dis_float=0.1178.ckpt"
mail: false
model_mode: fit

model:
  df_load: True
  df_refiner: "/media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_refine_model_69_0.009449292959118935.pth"
  df_pose_estimator: "/media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_model_26_0.012863246640872631.pth"
  df_refine: True
  df_w_normal: 0.015
  df_w_normal_rate: 0.3
  df_refine_iterations: 1
  df_dump_pred_pickle: True
  inital_pose:
    mode: "DenseFusionInit" # 'TransNoise' 'RotTransNoise'  'RotNoise'
    translation_noise_inital: 0.03
    rot_noise_deg_inital: 5
  mask:
    real_mask: True
    render_mask: True
    real_depth_mask: True
    render_depth_mask: True
  sem_seg: True

epochs: 500
lr: 1.0e-5
lr_cfg:
  on_plateau_cfg:
    mode: "min"
    factor: 0.3
    threshold: 0.02
  interval: "epoch"
  frequency: 1

vm:
  nr_of_images_per_object: 2500
  load_images: False

eval:
  threshold_add: 0.02

training:
  accumulate_grad_batches: 1
  progress_bar_refresh_rate: 1
  refine_iterations: 1
  refine_iterations_range: 0 # iteareatioons elemen refine_iterations +- refine_iterations_range
  max_epochs: 1000
  clamp_delta_t_pred: 0.1
  trans_deviation_resample_inital_pose: 0.3
  limit_train_batches: 50
  limit_val_batches: 5

visu:
  number_images_log_test: 2
  number_images_log_val: 2
  network_input_batch: True
  log_to_file: True

early_stopping_cfg:
  patience: 100

decay_margin_start: 0.016
samples_early_break_epoch: 5000000
time_early_break_epoch: 10
samples_early_break_validation: 100000
time_early_break_validation: 10

loader:
  batch_size: 2
  num_workers: 10
  shuffle: True
  pin_memory: True

d_test:
  name: "ycb"
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 2300
  num_pt_mesh_large: 2300
  obj_list_fil: null # if not null add list with specific elements -12 -17 is agood mix in general (starting at 0-20) for 21 objects
  obj_list_sym:
    - 12
    - 15
    - 18
    - 19
    - 20
  batch_list_cfg:
    sequence_names: null #either null or what name should be in the sequence for example to only plot hard interactions
    seq_length: 1
    fixed_length: true
    sub_sample: 1
    mode: "test" #dense_fusion_test
    add_syn_to_train: false
  noise_cfg:
    status: false
    noise_trans: 0.0
  output_cfg:
    return_same_size_tensors: true
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: true
    add_mask_image: true
    visu:
      status: true
      return_img: true

d_train:
  name: "ycb"
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 2300
  num_pt_mesh_large: 2300
  obj_list_fil: null # if not null add list with specific elements
  obj_list_sym:
    - 12
    - 15
    - 18
    - 19
    - 20
  batch_list_cfg:
    sequence_names: null #either null or what name should be in the sequence for example to only plot hard interactions
    seq_length: 1
    no_list_for_sequence_len_one: True
    fixed_length: true
    sub_sample: 1
    mode: "train"
    add_syn_to_train: true
  noise_cfg:
    status: false
    noise_trans: 0
  output_cfg:
    return_same_size_tensors: true
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: true
    add_mask_image: true
    visu:
      status: true
      return_img: true
