model_path: /cluster/work/riner/users/PLR-2020/yavays/models/runs/flow-disp/all-obj-lr-4-0.1-semseg-plato-05
flownet: false
checkpoint_restore: false
checkpoint_load: /media/scratch1/jonfrey/models/runs/cluster_disp_16/2020-11-08T00:36:57_b4_res2_loss_5to1_lr5-4_no_depth_no_skip_24h/epoch=96-avg_val_disparity_float=15.5202.ckpt
mail: false
model_mode: fit
model:
  df_load: false
  df_refiner: /media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_refine_model_69_0.009449292959118935.pth
  df_pose_estimator: /media/scratch1/jonfrey/models/trained_checkpoints/ycb/pose_model_26_0.012863246640872631.pth
  df_refine: false
  df_w_normal: 0.015
  df_w_normal_rate: 0.3
  df_refine_iterations: 1
  df_dump_pred_pickle: false
  inital_pose:
    mode: RotTransNoise
    translation_noise_inital: 0.02
    rot_noise_deg_inital: 30
  mask:
    real_mask: true
    render_mask: true
    real_depth_mask: true
    render_depth_mask: true
  sem_seg: true
efficient_disp_cfg:
  num_classes: 22
  backbone: efficientnet-b3
  seperate_flow_head: false
  pred_flow_pyramid: true
  pred_flow_pyramid_add: true
  ced_real: 3
  ced_render: 1
  ced_render_d: 0
  ced_real_d: 0
refine_cfg:
  iterations: 1
  feedback: pred_flow_gt_label
training_params_limit: true
loss:
  weight_semantic_segmentation: 0.1
  weight_flow: 1
  weight_flow_l1: 0
  weight_pose: 0
  weight_trans: 0
epochs: 500
lr: 0.0001
lr_cfg:
  on_plateau_cfg:
    mode: min
    factor: 0.5
    threshold: 0.1
  interval: epoch
  frequency: 1
vm:
  nr_of_images_per_object: 2500
  load_images: false
eval:
  threshold_add: 0.02
trainer:
  num_nodes: 1
  precision: 16
  auto_lr_find: false
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 1500
  limit_val_batches: 10
  limit_test_batches: 1500
  progress_bar_refresh_rate: 1
  max_epochs: 100
  terminate_on_nan: false
  profiler: false
  gpus: -1
  num_sanity_val_steps: 0
training:
  refine_iterations: 1
  refine_iterations_range: 0
  clamp_delta_t_pred: 0.1
  trans_deviation_resample_inital_pose: 0.3
visu:
  number_images_log_train: 0
  number_images_log_test: 0
  number_images_log_val: 0
  network_input_batch: false
  log_to_file: true
  always_calculate: false
  full_val: false
early_stopping_cfg:
  patience: 100
loader:
  batch_size: 16
  num_workers: 18
  shuffle: true
  pin_memory: true
d_test:
  name: ycb
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 2300
  num_pt_mesh_large: 2300
  obj_list_fil: null
  obj_list_sym:
  - 12
  - 15
  - 18
  - 19
  - 20
  batch_list_cfg:
    sequence_names: null
    seq_length: 1
    fixed_length: true
    sub_sample: 1
    mode: dense_fusion_test
    add_syn_to_train: false
  noise_cfg:
    status: false
    noise_trans: 0.0
  flow_cfg:
    sub: 2
    min_matches: 50
    dil_kernel_size: 2
    min_vis_size: 200
    max_matches: 10000
    max_iterations: 10000
  output_cfg:
    overfitting_nr_idx: -1
    vm_in_dataloader: true
    noise_translation: 0.02
    noise_rotation: 30
    return_same_size_tensors: true
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: true
    add_mask_image: true
    norm_render: false
    color_jitter_render:
      active: false
      cfg:
      - 0.2
      - 0.2
      - 0.2
      - 0.05
    norm_real: false
    color_jitter_real:
      active: false
      cfg:
      - 0.2
      - 0.2
      - 0.2
      - 0.05
    visu:
      status: true
      return_img: true
d_train:
  name: ycb
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 2300
  num_pt_mesh_large: 2300
  obj_list_fil: null
  obj_list_sym:
  - 12
  - 15
  - 18
  - 19
  - 20
  batch_list_cfg:
    sequence_names: null
    seq_length: 1
    no_list_for_sequence_len_one: true
    fixed_length: true
    sub_sample: 1
    mode: dense_fusion_train
    add_syn_to_train: true
  noise_cfg:
    status: false
    noise_trans: 0
  flow_cfg:
    sub: 2
    min_matches: 50
    dil_kernel_size: 2
    min_vis_size: 200
    max_matches: 2000
    max_iterations: 10000
  output_cfg:
    overfitting_nr_idx: -1
    vm_in_dataloader: true
    noise_translation: 0.02
    noise_rotation: 30
    return_same_size_tensors: true
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: true
    add_mask_image: true
    norm_render: false
    color_jitter_render:
      active: false
      cfg:
      - 0.2
      - 0.2
      - 0.2
      - 0.05
    norm_real: false
    color_jitter_real:
      active: false
      cfg:
      - 0.2
      - 0.2
      - 0.2
      - 0.05
    visu:
      status: true
      return_img: true
