model_path: "/cluster/work/riner/users/PLR-2020/jonfrey/models/runs/efficient_disparity_b1/validate_obj2_performance"

checkpoint_restore: True 
checkpoint_load: /cluster/work/riner/users/PLR-2020/jonfrey/models/runs/efficient_disparity_b1/2020-10-27T09:29:39_non_overfit_24h_lr-3_obj2_loaded4h/epoch=6-avg_val_dis_float=12.1321.ckpt
mail: false
model_mode: fit

model:
  df_load: False
  df_refiner: "/cluster/work/riner/users/PLR-2020/jonfrey/models/trained_checkpoints/ycb/pose_refine_model_69_0.009449292959118935.pth"
  df_pose_estimator: "/cluster/work/riner/users/PLR-2020/jonfrey/models/trained_checkpoints/ycb/pose_model_26_0.012863246640872631.pth"
  df_refine: False
  df_w_normal: 0.015
  df_w_normal_rate: 0.3
  df_refine_iterations: 1
  df_dump_pred_pickle: False
  inital_pose:
    mode: "RotTransNoise" # 'TransNoise' 'RotTransNoise'  'RotNoise'
    translation_noise_inital: 0.02
    rot_noise_deg_inital: 30
  mask:
    real_mask: True
    render_mask: True
    real_depth_mask: True
    render_depth_mask: True
  sem_seg: True

loss:
  weight_semantic_segmentation: 1
  weight_flow: 1
  weight_pose: 0
  weight_trans: 1

epochs: 500
lr: 1.0e-5
lr_cfg:
  on_plateau_cfg:
    mode: "min"
    factor: 0.95
    threshold: 0.02
  interval: "epoch"
  frequency: 1

vm:
  nr_of_images_per_object: 2500
  load_images: False

eval:
  threshold_add: 0.02

trainer:
  num_nodes: 1
  precision: 16
  auto_lr_find: false
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 10
  limit_val_batches: 10 #1.0 is all 0.5 is half the dataset and 50 are 50 batches
  limit_test_batches: 5
  progress_bar_refresh_rate: 1
  max_epochs: 100
  terminate_on_nan: false
  profiler: false
  gpus: 1
  num_sanity_val_steps: 0

training:
  refine_iterations: 1
  refine_iterations_range: 0 # iteareatioons elemen refine_iterations +- refine_iterations_range
  clamp_delta_t_pred: 0.1
  trans_deviation_resample_inital_pose: 0.3

visu:
  number_images_log_train: 10
  number_images_log_test: 5
  number_images_log_val: 10
  network_input_batch: False
  log_to_file: False
  always_calculate: False
  full_val: True

early_stopping_cfg:
  patience: 100

loader:
  batch_size: 8
  num_workers: 18
  shuffle: True
  pin_memory: True

d_test:
  name: "ycb"
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 2300
  num_pt_mesh_large: 2300
  obj_list_fil: null #null # if not null add list with specific elements -12 -17 is agood mix in general (starting at 0-20) for 21 objects
  obj_list_sym:
    - 12
    - 15
    - 18
    - 19
    - 20
  batch_list_cfg:
    sequence_names: null #either null or what name should be in the sequence for example to only plot hard interactions
    seq_length: 1
    fixed_length: true
    sub_sample: 1
    mode: "test" #dense_fusion_test
    add_syn_to_train: false
  noise_cfg:
    status: false
    noise_trans: 0.0
  output_cfg:
    overfitting_nr_idx: 10
    vm_in_dataloader: true
    noise_translation: 0.04
    noise_rotation: 20
    return_same_size_tensors: true
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: true
    add_mask_image: true
    norm_render: false
    color_jitter_render:
      active: false
      cfg:
        - 0.2
        - 0.2
        - 0.2
        - 0.05
    norm_real: false
    color_jitter_real:
      active: false
      cfg:
        - 0.2
        - 0.2
        - 0.2
        - 0.05
    visu:
      status: true
      return_img: true

d_train:
  name: "ycb"
  objects: 21
  num_points: 1000
  num_pt_mesh_small: 2300
  num_pt_mesh_large: 2300
  obj_list_fil: #null # if not null add list with specific elements
    - 2
  obj_list_sym:
    - 12
    - 15
    - 18
    - 19
    - 20
  batch_list_cfg:
    sequence_names: null #either null or what name should be in the sequence for example to only plot hard interactions
    seq_length: 1
    no_list_for_sequence_len_one: True
    fixed_length: true
    sub_sample: 1
    mode: "train"
    add_syn_to_train: true
  noise_cfg:
    status: false
    noise_trans: 0
  output_cfg:
    overfitting_nr_idx: -1
    vm_in_dataloader: true
    noise_translation: 0.03
    noise_rotation: 30
    return_same_size_tensors: true
    force_one_object_visible: true
    status: false
    refine: false
    add_depth_image: true
    add_mask_image: true
    norm_render: false
    color_jitter_render:
      active: false
      cfg:
        - 0.2
        - 0.2
        - 0.2
        - 0.05
    norm_real: false
    color_jitter_real:
      active: false
      cfg:
        - 0.2
        - 0.2
        - 0.2
        - 0.05
    visu:
      status: true
      return_img: true
